apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-web-service-gin
description: main application pipeline
serialPipeline:
  stages:
  - targetId: test-private
  - targetId: staging-private
  - targetId: prod-private
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test-private
description: Web Service Gin development service
run:
  location: projects/vault-on-cloud-run-419505/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging-private
description: Web Service Gin staging service
run:
  location: projects/vault-on-cloud-run-419505/locations/us-central1